// Generated by pnpm bindings.

export type Board = {
	hexes: Array<Hex>;
	vertices: Array<Vertex>;
	edges: Array<Edge>;
	harbors: Array<Harbor>;
};

export type Chat = { name: string; text: string; time: number };

export type ClientView = {
	identity: Identity;
	room: RoomView | null;
	connection: Connection;
	addresses: Array<string>;
	nearby: Array<RoomInfo>;
	recent: Array<RoomInfo>;
	saves: Array<SavedGame>;
};

export type Connection = "home" | "connecting" | "connected" | "disconnected";

export type Edge = { vertices: [number, number]; hexes: Array<number> };

export type Harbor = { edge: number; resource: Resource | null };

export type Hex = {
	x: number;
	y: number;
	terrain: Terrain;
	number: number;
	vertices: [number, number, number, number, number, number];
	edges: [number, number, number, number, number, number];
	neighbors: Array<number>;
};

export type Identity = { token: string; name: string; color: number };

export type Mode = "base" | "cities";

export type Request =
	| { type: "join"; identity: Identity }
	| { type: "action"; action: RoomAction };

export type Resource =
	| "wood"
	| "brick"
	| "wool"
	| "grain"
	| "ore"
	| "cloth"
	| "coin"
	| "paper";

export type Response =
	| { type: "state"; room: RoomView }
	| { type: "error"; message: string };

export type RoomAction =
	| { type: "configure"; settings: RoomSettings }
	| { type: "profile"; name: string; color: number }
	| { type: "ready"; ready: boolean }
	| { type: "chat"; text: string };

export type RoomInfo = {
	id: string;
	name: string;
	addresses: Array<string>;
	players: number;
	capacity: number;
	mode: Mode;
	started: boolean;
};

export type RoomSettings = {
	name: string;
	mode: Mode;
	capacity: number;
	starter: number | null;
};

export type RoomView = {
	id: string;
	settings: RoomSettings;
	seats: Array<Seat>;
	spectators: Array<string>;
	you: number | null;
	host: boolean;
	chat: Array<Chat>;
};

export type SavedGame = {
	id: string;
	name: string;
	mode: Mode;
	players: Array<string>;
	updated: number;
};

export type Seat = {
	name: string;
	color: number;
	connected: boolean;
	ready: boolean;
};

export type Terrain =
	| "forest"
	| "hills"
	| "pasture"
	| "fields"
	| "mountains"
	| "desert";

export type Vertex = {
	x: number;
	y: number;
	neighbors: Array<number>;
	edges: Array<number>;
	hexes: Array<number>;
};
