// Generated by pnpm bindings.

export type Chat = { name: string; text: string; time: number };

export type ClientView = {
	identity: Identity;
	room: RoomView | null;
	connection: Connection;
	addresses: Array<string>;
	nearby: Array<RoomInfo>;
};

export type Connection = "home" | "connecting" | "connected" | "disconnected";

export type Identity = { token: string; name: string; color: number };

export type Mode = "base" | "cities";

export type Request =
	| { type: "join"; identity: Identity }
	| { type: "action"; action: RoomAction };

export type Response =
	| { type: "state"; room: RoomView }
	| { type: "error"; message: string };

export type RoomAction =
	| { type: "configure"; settings: RoomSettings }
	| { type: "profile"; name: string; color: number }
	| { type: "ready"; ready: boolean }
	| { type: "chat"; text: string };

export type RoomInfo = {
	id: string;
	name: string;
	addresses: Array<string>;
	players: number;
	capacity: number;
	mode: Mode;
	started: boolean;
};

export type RoomSettings = {
	name: string;
	mode: Mode;
	capacity: number;
	starter: number | null;
};

export type RoomView = {
	id: string;
	settings: RoomSettings;
	seats: Array<Seat>;
	spectators: Array<string>;
	you: number | null;
	host: boolean;
	chat: Array<Chat>;
};

export type Seat = {
	name: string;
	color: number;
	connected: boolean;
	ready: boolean;
};
