// Generated by pnpm bindings.

export type Action =
	| { type: "recruitKnight"; vertex: number }
	| { type: "promoteKnight"; vertex: number }
	| { type: "activateKnight"; vertex: number }
	| { type: "moveKnight"; vertex: number }
	| { type: "expelRobber"; vertex: number }
	| { type: "retireKnight"; vertex: number }
	| { type: "improve"; track: Track }
	| { type: "buildWall"; vertex: number }
	| { type: "tokens"; action: TokenAction }
	| { type: "buildSettlement"; vertex: number }
	| { type: "buildRoad"; edge: number }
	| { type: "buildCity"; vertex: number }
	| { type: "bankTrade"; give: Resource; take: Resource }
	| {
			type: "offerTrade";
			give: [number, number, number, number, number, number, number, number];
			want: [number, number, number, number, number, number, number, number];
	  }
	| { type: "respondTrade"; accept: boolean }
	| { type: "completeTrade"; partner: number }
	| { type: "cancelTrade" }
	| { type: "buyDevelopment" }
	| { type: "playCard"; card: Card }
	| { type: "roll" }
	| { type: "endTurn" }
	| { type: "pick"; value: number }
	| {
			type: "selectCards";
			cards: [number, number, number, number, number, number, number, number];
	  }
	| { type: "skip" };

export type AvailableAction = {
	action: Action;
	label: string;
	target: Target | null;
	cost: [number, number, number, number, number, number, number, number];
};

export type Awards = {
	road: number | null;
	army: number | null;
	lengths: Array<number>;
};

export type Board = {
	hexes: Array<Hex>;
	vertices: Array<Vertex>;
	edges: Array<Edge>;
	harbors: Array<Harbor>;
};

export type Building = { player: number; kind: BuildingKind };

export type BuildingKind = "settlement" | "city";

export type Card =
	| "knight"
	| "victoryPoint"
	| "roadBuilding"
	| "plenty"
	| "monopoly";

export type CardChoice = {
	available: [number, number, number, number, number, number, number, number];
	count: number;
};

export type CardView = {
	card: Card;
	name: string;
	description: string;
	playable: boolean;
};

export type Chat = { name: string; text: string; time: number };

export type CityView = {
	barbarians: number;
	attacks: number;
	event: EventDie | null;
	decks: [number, number, number];
	knights: Array<Knight | null>;
	defense: Array<number>;
	upgrades: Array<[number, number, number]>;
	walls: Array<number>;
	metropolises: [number | null, number | null, number | null];
	ruins: Array<number>;
};

export type ClientView = {
	identity: Identity;
	room: RoomView | null;
	connection: Connection;
	addresses: Array<string>;
	nearby: Array<RoomInfo>;
	recent: Array<RoomInfo>;
	saves: Array<SavedGame>;
};

export type Connection = "home" | "connecting" | "connected" | "disconnected";

export type Edge = { vertices: [number, number]; hexes: Array<number> };

export type EventDie = "barbarians" | "trade" | "politics" | "science";

export type GameEvent = {
	seq: number;
	player: number | null;
	kind: string;
	text: string;
	target: Target | null;
};

export type GameView = {
	cities: CityView | null;
	mode: Mode;
	humans: number;
	tokens: number;
	board: Board;
	players: Array<PlayerView>;
	buildings: Array<Building | null>;
	roads: Array<number | null>;
	bank: [number, number, number, number, number, number, number, number];
	robber: number | null;
	stage: Stage;
	turn: Turn;
	private: PrivateView | null;
	actions: Array<AvailableAction>;
	prompt: Prompt | null;
	trade: Trade | null;
	awards: Awards;
	development: number;
	events: Array<GameEvent>;
	winner: number | null;
};

export type Harbor = { edge: number; resource: Resource | null };

export type Hex = {
	x: number;
	y: number;
	terrain: Terrain;
	number: number;
	vertices: [number, number, number, number, number, number];
	edges: [number, number, number, number, number, number];
	neighbors: Array<number>;
};

export type Identity = { token: string; name: string; color: number };

export type Improvement = {
	track: Track;
	level: number;
	name: string;
	next: string | null;
	cost: [number, number, number, number, number, number, number, number];
};

export type Knight = {
	player: number;
	level: number;
	active: boolean;
	activated: number;
	upgraded: number;
};

export type Mode = "base" | "cities";

export type Pick = { value: number; label: string; target: Target | null };

export type PlayerView = {
	name: string;
	color: number;
	points: number;
	handCount: number;
	cardCount: number;
	army: number;
	defender: number;
	revealed: Array<Progress>;
	tokens: number;
	roads: number;
	settlements: number;
	cities: number;
};

export type PrivateView = {
	progress: Array<Progress>;
	improvements: Array<Improvement>;
	handLimit: number;
	canOffer: boolean;
	hand: [number, number, number, number, number, number, number, number];
	points: number;
	rates: [number, number, number, number, number, number, number, number];
	cards: Array<CardView>;
};

export type Progress =
	| "commercialHarbor"
	| "guildDues"
	| "merchant"
	| "merchantFleet"
	| "resourceMonopoly"
	| "commodityMonopoly"
	| "diplomacy"
	| "encouragement"
	| "espionage"
	| "intrigue"
	| "sabotage"
	| "taxation"
	| "treason"
	| "constitution"
	| "wedding"
	| "alchemy"
	| "crane"
	| "engineering"
	| "invention"
	| "irrigation"
	| "medicine"
	| "mining"
	| "roadBuilding"
	| "smithing"
	| "printing";

export type Prompt = {
	player: number;
	title: string;
	choices: Array<Pick>;
	cards: CardChoice | null;
	canSkip: boolean;
};

export type Request =
	| { type: "join"; identity: Identity }
	| { type: "action"; action: RoomAction };

export type Resource =
	| "wood"
	| "brick"
	| "wool"
	| "grain"
	| "ore"
	| "cloth"
	| "coin"
	| "paper";

export type Response =
	| { type: "state"; room: RoomView }
	| { type: "error"; message: string };

export type RoomAction =
	| { type: "start" }
	| { type: "game"; action: Action }
	| { type: "configure"; settings: RoomSettings }
	| { type: "profile"; name: string; color: number }
	| { type: "ready"; ready: boolean }
	| { type: "chat"; text: string };

export type RoomInfo = {
	id: string;
	name: string;
	addresses: Array<string>;
	players: number;
	capacity: number;
	mode: Mode;
	started: boolean;
};

export type RoomSettings = {
	name: string;
	mode: Mode;
	capacity: number;
	starter: number | null;
};

export type RoomView = {
	id: string;
	settings: RoomSettings;
	seats: Array<Seat>;
	spectators: Array<string>;
	you: number | null;
	host: boolean;
	chat: Array<Chat>;
	game: GameView | null;
};

export type SavedGame = {
	id: string;
	name: string;
	mode: Mode;
	players: Array<string>;
	updated: number;
};

export type Seat = {
	name: string;
	color: number;
	connected: boolean;
	ready: boolean;
};

export type Stage =
	| { type: "setup"; step: number; road: number | null }
	| { type: "production" }
	| { type: "action" }
	| { type: "ended" };

export type Target =
	| { type: "vertex"; id: number }
	| { type: "edge"; id: number }
	| { type: "hex"; id: number };

export type Terrain =
	| "forest"
	| "hills"
	| "pasture"
	| "fields"
	| "mountains"
	| "desert";

export type TokenAction =
	| { type: "trade"; commodities: boolean }
	| { type: "moveRobber" }
	| { type: "sacrifice" };

export type Track = "trade" | "politics" | "science";

export type Trade = {
	player: number;
	give: [number, number, number, number, number, number, number, number];
	want: [number, number, number, number, number, number, number, number];
	responses: Array<boolean | null>;
};

export type Turn = {
	player: number;
	primary: number;
	number: number;
	dice: Array<[number, number]>;
	development: boolean;
	tokenAction: boolean;
	sacrifice: boolean;
};

export type Vertex = {
	x: number;
	y: number;
	neighbors: Array<number>;
	edges: Array<number>;
	hexes: Array<number>;
};
